baseURL = 'http://about.kakati.email/himadree/'
languageCode = 'en-us'
title = 'Himadree Das'
theme = 'hyde'

[Menu]
    main = [
        {Name = "Curriculum Vitae", URL = "/CV.pdf"}
    ]

[params]
    description = "Brief summary of my doctoral research progress"
    layoutReverse = true